package mystic.assets.exporters

import mystic.assets.config.BrandConfig
import java.awt.Color
import java.io.File

class CssExporter(private val outputDir: File) {

    fun export(config: BrandConfig): File {
        val dir = File(outputDir, "css")
        dir.mkdirs()
        val file = File(dir, "brand.css")

        val css = buildString {
            appendLine("/* Mystic Brand Tokens — Generated by mystic-assets */")
            appendLine(":root {")
            appendLine("  /* Primary */")
            appendLine("  --mystic-primary: ${hex(config.colors.primary)};")
            appendLine("  --mystic-primary-dark: ${hex(config.colors.primaryDark)};")
            appendLine("  --mystic-primary-light: ${hex(config.colors.primaryLight)};")
            appendLine()
            appendLine("  /* Dark Theme Backgrounds */")
            appendLine("  --mystic-bg-dark: ${hex(config.colors.backgroundDark)};")
            appendLine("  --mystic-bg-surface: ${hex(config.colors.backgroundSurface)};")
            appendLine("  --mystic-bg-panel: ${hex(config.colors.backgroundPanel)};")
            appendLine("  --mystic-bg-elevated: ${hex(config.colors.backgroundElevated)};")
            appendLine()
            appendLine("  /* Dark Theme Foregrounds */")
            appendLine("  --mystic-fg-primary: ${hex(config.colors.foregroundPrimary)};")
            appendLine("  --mystic-fg-secondary: ${hex(config.colors.foregroundSecondary)};")
            appendLine("  --mystic-fg-muted: ${hex(config.colors.foregroundMuted)};")
            appendLine("  --mystic-fg-border: ${hex(config.colors.foregroundBorder)};")
            appendLine()
            appendLine("  /* Light Theme */")
            appendLine("  --mystic-light-bg: ${hex(config.colors.lightBackground)};")
            appendLine("  --mystic-light-fg: ${hex(config.colors.lightForeground)};")
            appendLine("  --mystic-light-muted: ${hex(config.colors.lightMuted)};")
            appendLine("  --mystic-light-surface: ${hex(config.colors.lightSurface)};")
            appendLine()
            appendLine("  /* Accents */")
            appendLine("  --mystic-accent-gold: ${hex(config.colors.accentGold)};")
            appendLine("  --mystic-accent-rose: ${hex(config.colors.accentRose)};")
            appendLine("  --mystic-accent-seafoam: ${hex(config.colors.accentSeafoam)};")
            appendLine("  --mystic-accent-lavender: ${hex(config.colors.accentLavender)};")
            appendLine("  --mystic-accent-ivory: ${hex(config.colors.accentIvory)};")
            appendLine()
            appendLine("  /* Typography */")
            appendLine("  --mystic-font-display: '${config.typography.display}', system-ui, sans-serif;")
            appendLine("  --mystic-font-body: '${config.typography.body}', system-ui, sans-serif;")
            appendLine("  --mystic-font-mono: '${config.typography.mono}', ui-monospace, monospace;")
            appendLine("  --mystic-tracking: ${config.typography.tracking}em;")
            appendLine("}")
            appendLine()
            appendLine("/* Utility classes */")
            appendLine(".mystic-text-primary { color: var(--mystic-fg-primary); }")
            appendLine(".mystic-text-muted { color: var(--mystic-fg-muted); }")
            appendLine(".mystic-text-accent { color: var(--mystic-primary); }")
            appendLine(".mystic-bg-dark { background-color: var(--mystic-bg-dark); }")
            appendLine(".mystic-bg-surface { background-color: var(--mystic-bg-surface); }")
            appendLine(".mystic-bg-panel { background-color: var(--mystic-bg-panel); }")
        }

        file.writeText(css)
        return file
    }

    private fun hex(c: Color): String =
        "#%02X%02X%02X".format(c.red, c.green, c.blue)
}
